apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "deployment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: app
    protocol: {{ default "TCP" .Values.protocol }}
    port: {{ .Values.exposedPort }}
    targetPort: {{ .Values.containerPort }}
  {{- if .Values.esp }}
  - name: esp
    protocol: {{ default "TCP" .Values.protocol }}
    port: {{ .Values.esp.containerPort }}
    targetPort: {{ .Values.esp.containerPort }}
  {{- end }}
